# Generated by Django 4.0.1 on 2022-02-14 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('introduction', models.CharField(max_length=100)),
                ('dream', models.CharField(max_length=200)),
                ('pictures', models.ImageField(upload_to='pictures/')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
