# Generated by Django 4.0.1 on 2022-02-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dreams',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
