# Generated by Django 4.0.1 on 2022-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_dreams_user_introduction_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
