# Generated by Django 4.0.1 on 2022-02-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_website_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dreams',
            new_name='dream',
        ),
    ]
