# Generated by Django 4.0.1 on 2022-02-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
