# Generated by Django 4.0.1 on 2022-02-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_facebook_link_user_twitter_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
