# Generated by Django 4.0.1 on 2022-02-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_facebook_link_remove_user_twitter_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_username',
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
