# Generated by Django 4.0.1 on 2022-02-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_diary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='contect',
            new_name='content',
        ),
    ]
