# Generated by Django 4.0.1 on 2022-02-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_contect_diary_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
