# Generated by Django 4.0.1 on 2022-02-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_diary_diary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diary_content',
            },
        ),
        migrations.CreateModel(
            name='DiaryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diary_title',
            },
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.AddField(
            model_name='diarycontent',
            name='diary_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.diarytitle'),
        ),
        migrations.AddField(
            model_name='diarycontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
