# Generated by Django 4.0.1 on 2022-02-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_diarycontent_diarytitle_delete_diary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarycontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
