# Generated by Django 4.0.1 on 2022-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_diarycontent_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarytitle',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
