# Generated by Django 4.0.1 on 2022-02-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_diarytitle_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarytitle',
            old_name='is_private',
            new_name='is_public',
        ),
    ]
