# Generated by Django 4.0.1 on 2022-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_is_private_diarytitle_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarytitle',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
