# Generated by Django 4.0.1 on 2022-02-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_diarytitle_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycontent',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
