# Generated by Django 4.0.1 on 2022-02-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_diarycontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycontent',
            name='content',
            field=models.CharField(max_length=700),
        ),
    ]
