# Generated by Django 4.0.1 on 2022-02-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_diarycontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycontent',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
