# Generated by Django 4.0.1 on 2022-02-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_diarycontent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
