# Generated by Django 4.0.2 on 2022-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycontent',
            name='content',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
