# Generated by Django 4.0.2 on 2022-02-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_diarycontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.FileField(null=True, upload_to='icons/'),
        ),
    ]
