# Generated by Django 4.0.2 on 2022-02-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_user_image_user_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='favorite',
        ),
    ]
