# Generated by Django 4.0.2 on 2022-03-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_thread_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='sender',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='receiver',
            new_name='user2',
        ),
    ]
