# Generated by Django 4.0.2 on 2022-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_rename_sender_thread_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dream',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
