# Generated by Django 4.0.2 on 2022-03-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_user_dream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.FileField(default='../static/css/img/default.png', upload_to='icons/'),
        ),
    ]
