# Generated by Django 4.0.2 on 2022-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='icons/default_jjjs8l.png', upload_to='icons/'),
        ),
    ]
