# Generated by Django 4.0.2 on 2022-03-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_diarycontent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarycontent',
            name='image',
        ),
        migrations.AddField(
            model_name='diarycontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='attached_photo/'),
        ),
    ]
