# Generated by Django 4.0.2 on 2022-03-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_diarycontent_image_diarycontent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(null=True, upload_to='backgrounds/'),
        ),
    ]
